#! /bin/bash  
./gradlew copyDebugLint
./gradlew checkDebugManifest
./gradlew packageDebugJar
./gradlew compileDebugNdk
./gradlew packageDebugJniLibs
./gradlew packageDebugLocalJar
./gradlew packageDebugRenderscript
./gradlew packageDebugResources
./gradlew bundleDebug
./gradlew prepareReleaseDependencies
./gradlew compileReleaseAidl
./gradlew compileReleaseRenderscript
./gradlew generateReleaseBuildConfig
./gradlew generateReleaseAssets
./gradlew mergeReleaseAssets
./gradlew generateReleaseResValues
./gradlew generateReleaseResources
./gradlew mergeReleaseResources
./gradlew processReleaseManifest
./gradlew processReleaseResources
./gradlew generateReleaseSources
./gradlew processReleaseJavaRes
./gradlew compileReleaseJavaWithJavac
./gradlew extractReleaseAnnotations
./gradlew mergeReleaseProguardFiles
./gradlew packageReleaseJar
./gradlew compileReleaseNdk
./gradlew packageReleaseJniLibs
./gradlew packageReleaseLocalJar
./gradlew packageReleaseRenderscript
./gradlew packageReleaseResources
./gradlew bundleRelease
./gradlew preStore360ReleaseBuild
./gradlew prepareComAndroidSupportAppcompatV72311Library
./gradlew prepareComAndroidSupportCardviewV72311Library
./gradlew prepareComAndroidSupportDesign2311Library
./gradlew prepareComAndroidSupportMultidex101Library
./gradlew prepareComAndroidSupportPaletteV72311Library
./gradlew prepareComAndroidSupportRecyclerviewV72311Library
./gradlew prepareComAndroidSupportSupportV132311Library
./gradlew prepareComAndroidSupportSupportV42311Library
./gradlew prepareComCommit451PhotoView124Library
./gradlew prepareComEvernoteAndroidSdk200RC3Library
./gradlew prepareComSquareupLeakcanaryLeakcanaryAndroid13Library
./gradlew prepareComYydcdutSdlvSdlv040Library
./gradlew prepareIoReactivexRxandroid101Library
./gradlew prepareNetVrallevAndroidAndroidTask107Library
./gradlew preparePhotoNoterPG_Edit_SDKUnspecifiedLibrary
./gradlew prepareStore360DebugDependencies
./gradlew compileStore360DebugAidl
./gradlew compileStore360DebugRenderscript
./gradlew generateStore360DebugBuildConfig
./gradlew generateStore360DebugAssets
./gradlew mergeStore360DebugAssets
./gradlew generateStore360DebugResValues
./gradlew generateStore360DebugResources
./gradlew mergeStore360DebugResources
./gradlew processStore360DebugManifest
./gradlew processStore360DebugResources
./gradlew generateStore360DebugSources
./gradlew processStore360DebugJavaRes
./gradlew compileStore360DebugJavaWithJavac
./gradlew compileRetrolambdaStore360Debug
./gradlew compileStore360DebugNdk
./gradlew compileStore360DebugSources
./gradlew collectStore360DebugMultiDexComponents
./gradlew packageAllStore360DebugClassesForMultiDex
./gradlew shrinkStore360DebugMultiDexComponents
./gradlew createStore360DebugMainDexClassList
./gradlew dexStore360Debug
./gradlew validateDebugSigning
./gradlew packageStore360Debug
./gradlew zipalignStore360Debug
./gradlew assembleStore360Debug
