/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yydcdut_note_utils_RxImageBlur */

#ifndef _Included_com_yydcdut_note_utils_RxImageBlur
#define _Included_com_yydcdut_note_utils_RxImageBlur
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yydcdut_note_utils_RxImageBlur
 * Method:    blur
 * Signature: (Landroid/graphics/Bitmap;I)V
 */
JNIEXPORT void JNICALL Java_com_yydcdut_note_utils_RxImageBlur_blur
        (JNIEnv *, jobject, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
